# -*- coding: utf-8 -*-
"""ADENS version 0.80

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qW9SDg99UG3YCoZ5bvEzmTVAi4nM6Oia
"""

import ipywidgets as widgets
from IPython.display import display, clear_output, Audio
import numpy as np
import time


def generar_sonido_acierto():
    sr = 12000
    t = np.linspace(0, 0.3, int(sr * 0.3))
    frecuencia = 880
    onda = np.sin(2 * np.pi * frecuencia * t) * np.exp(-15 * t)
    return Audio(onda, rate=sr, autoplay=True)

def generar_sonido_error():
    sr = 12000
    t = np.linspace(0, 0.4, int(sr * 0.4))
    frecuencia = 120
    onda = np.sign(np.sin(2 * np.pi * frecuencia * t)) * np.exp(-4 * t)
    return Audio(onda, rate=sr, autoplay=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import time
# 
# 
# def reproducir_sonido(tipo):
#     sr = 12000
#     t = np.linspace(0, 0.3 if tipo=="acierto" else 0.4, int(sr * (0.3 if tipo=="acierto" else 0.4)))
#     frecuencia = 880 if tipo=="acierto" else 120
#     if tipo == "acierto":
#         onda = np.sin(2 * np.pi * frecuencia * t) * np.exp(-15 * t)
#     else:
#         onda = np.sign(np.sin(2 * np.pi * frecuencia * t)) * np.exp(-4 * t)
#     st.audio(onda, sample_rate=sr, autoplay=True)
# 
# 
# banco_materias = {}
# materias_secundaria = {
#     "Matematicas": "🧮 Matemáticas", "Historia": "🏛️ Historia",
#     "Ciencias": "🔬 Ciencias", "Geografia": "🌍 Geografía"
# }
# 
# for clave, texto in materias_secundaria.items():
#     banco_materias[clave] = {"menu_texto": texto, "juegos": []}
#     for i in range(1, 51):
#         if clave == "Matematicas":
#             num1, num2 = i * 2, i + 5
#             banco_materias[clave]["juegos"].append({
#                 "titulo": f"Ecuaciones Básicas - Nivel {i}",
#                 "explicacion": f"Suma {num1} más {num2} para obtener el valor de X.",
#                 "pregunta": f"¿Cuánto vale X en: X = {num1} + {num2}?",
#                 "opciones": [str(num1+num2), str(num1+num2+3), str(num1+num2-2)],
#                 "correcta": str(num1+num2)
#             })
#         elif clave == "Historia":
#             año = 1400 + i
#             banco_materias[clave]["juegos"].append({
#                 "titulo": f"Línea del Tiempo - Nivel {i}",
#                 "explicacion": f"El año {año} pertenece a una época de grandes cambios.",
#                 "pregunta": f"¿A qué siglo pertenece el año {año}?",
#                 "opciones": ["Siglo XV", "Siglo XVI", "Siglo XVII"],
#                 "correcta": "Siglo XV" if año < 1500 else "Siglo XVI"
#             })
#         elif clave == "Ciencias":
#             banco_materias[clave]["juegos"].append({
#                 "titulo": f"Elementos y Células - Nivel {i}",
#                 "explicacion": f"El hidrógeno (H) tiene exactamente 1 protón en su núcleo.",
#                 "pregunta": f"¿Cuántos protones tiene el Hidrógeno en el nivel {i}?",
#                 "opciones": ["1", "2", "3"], "correcta": "1"
#             })
#         elif clave == "Geografia":
#             distancia = i * 100
#             banco_materias[clave]["juegos"].append({
#                 "titulo": f"Capas Atmosféricas - Nivel {i}",
#                 "explicacion": f"La troposfera llega hasta los primeros kilómetros.",
#                 "pregunta": f"Si un cohete sube {distancia} km, ¿en qué capa está?",
#                 "opciones": ["Troposfera", "Estratosfera", "Espacio Exterior"],
#                 "correcta": "Troposfera" if distancia < 12 else "Espacio Exterior" if distancia > 50 else "Estratosfera"
#             })
# 
# 
# lista_avatares_config = {
#     "⚪️ principiante": {"emoji": "⚪️", "nivel_req": 1},
#     "🌟 Estudiante": {"emoji": "🌟", "nivel_req": 2},
#     "🔥intermedio": {"emoji": "🔥", "nivel_req": 3},
#     "🧠 avanzado": {"emoji": "🧠", "nivel_req": 4},
#     "👑 estudiante ejemplar": {"emoji": "👑", "nivel_req": 5}
# }
# 
# 
# if "usuario" not in st.session_state:
#     st.session_state.usuario = {"nombre": "", "xp": 0, "nivel": 1, "aprobados": set(), "avatar_emoji": "⚪️", "avatar_nombre": "⚪️ principiante"}
# 
# 
# st.title("🏫 ADENS")
# 
# if st.session_state.usuario["nombre"] == "":
#     nombre_input = st.text_input("Introduce tu nombre para comenzar:")
#     if st.button("Ingresar a ADENS"):
#         if nombre_input.strip() != "":
#             st.session_state.usuario["nombre"] = nombre_input
#             st.rerun()
# else:
#     u = st.session_state.usuario
#     juegos_ganados = len(u["aprobados"])
#     porcentaje = int((juegos_ganados / 200) * 100)
# 
#     st.sidebar.markdown("### ⚙️ Configuración")
# 
#     opciones_visuales_avatar = []
#     mapeo_opciones = {}
# 
#     for nombre, datos in lista_avatares_config.items():
#         if u["nivel"] >= datos["nivel_req"]:
#             texto_visual = f"{datos['emoji']} {nombre}"
#         else:
#             texto_visual = f"🔒 {nombre} (Req. Nivel {datos['nivel_req']})"
#         opciones_visuales_avatar.append(texto_visual)
#         mapeo_opciones[texto_visual] = nombre
# 
# 
#     indice_defecto = 0
#     if u["avatar_nombre"] in lista_avatares_config:
#         for idx, texto in enumerate(opciones_visuales_avatar):
#             if mapeo_opciones[texto] == u["avatar_nombre"]:
#                 indice_defecto = idx
#                 break
# 
#     avatar_seleccionado = st.sidebar.selectbox(
#         "Elige tu foto de perfil:",
#         opciones_visuales_avatar,
#         index=indice_defecto
#     )
# 
# 
#     nombre_real_avatar = mapeo_opciones[avatar_seleccionado]
#     requisitos = lista_avatares_config[nombre_real_avatar]
# 
#     if u["nivel"] >= requisitos["nivel_req"]:
#         u["avatar_emoji"] = requisitos["emoji"]
#         u["avatar_nombre"] = nombre_real_avatar
#     else:
#         st.sidebar.error(f"⚠️ ¡Bloqueado! Sigue jugando para llegar al Nivel {requisitos['nivel_req']}.")
# 
#     st.sidebar.markdown("---")
# 
# 
#     st.sidebar.html(f"<h1 style='text-align: center; font-size: 80px; margin: 0;'>{u['avatar_emoji']}</h1>")
#     st.sidebar.markdown(f"### 👤 Estudiante: {u['nombre']}")
#     st.sidebar.markdown(f"🌟 **Nivel {u['nivel']}** | ✨ {u['xp']} XP")
#     st.sidebar.progress(juegos_ganados / 200)
#     st.sidebar.caption(f"Completado: {juegos_ganados}/200 ({porcentaje}%)")
# 
# 
#     materia_sel = st.selectbox("Selecciona una materia para estudiar:", list(banco_materias.keys()), format_func=lambda x: materias_secundaria[x])
# 
#     nivel_actual = 1
#     for i in range(1, 51):
#         if f"{materia_sel}_{i}" not in u["aprobados"]:
#             nivel_actual = i
#             break
# 
#     if f"{materia_sel}_50" in u["aprobados"]:
#         st.balloons()
#         st.success("¡Completaste todos los niveles de esta materia!")
#     else:
#         juego = banco_materias[materia_sel]["juegos"][nivel_actual - 1]
#         st.subheader(f"📚 {juego['titulo']} ({nivel_actual}/50)")
#         st.info(juego['explicacion'])
# 
#         respuesta = st.radio(juego['pregunta'], juego['opciones'], index=None)
# 
#         if st.button("Comprobar Respuesta ✔️"):
#             if respuesta == juego['correcta']:
#                 st.session_state.usuario["aprobados"].add(f"{materia_sel}_{nivel_actual}")
#                 st.session_state.usuario["xp"] += 1
# 
# 
#                 nuevo_nivel = (st.session_state.usuario["xp"] // 50) + 1
#                 if nuevo_nivel > st.session_state.usuario["nivel"]:
#                     st.session_state.usuario["nivel"] = nuevo_nivel
#                     st.toast("🎉 ¡Felicidades! Subiste de nivel y desbloqueaste nuevos avatares.")
# 
#                 st.success("¡Respuesta Correcta! +1 XP")
#                 reproducir_sonido("acierto")
#                 time.sleep(1)
#                 st.rerun()
#             else:
#                 st.error("Incorrecto. Intenta de nuevo.")
#                 reproducir_sonido("error")
#

import json
import os

# --- 💾 SISTEMA DE PERSISTENCIA (BASE DE DATOS EN ARCHIVO) ---
ARCHIVO_DATOS = "progreso_estudiantes.json"

def cargar_progreso_global():
    if os.path.exists(ARCHIVO_DATOS):
        with open(ARCHIVO_DATOS, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}

def guardar_progreso_usuario():
    progreso_total = cargar_progreso_global()
    # Convertimos el conjunto (set) a una lista para que sea compatible con JSON
    datos_guardar = {
        "nombre": usuario["nombre"],
        "avatar_estilo": usuario["avatar_estilo"],
        "xp": usuario["xp"],
        "nivel": usuario["nivel"],
        "niveles_aprobados": list(usuario["niveles_aprobados"])
    }
    progreso_total[usuario["nombre"].lower().strip()] = datos_guardar
    with open(ARCHIVO_DATOS, "w", encoding="utf-8") as f:
        json.dump(progreso_total, f, ensure_ascii=False, indent=4)

# --- ESTADO DEL JUGADOR ---
usuario = {
    "nombre": "",
    "avatar_estilo": "background: linear-gradient(135deg, #3498db, #2980b9);",
    "xp": 0,
    "nivel": 1,
    "niveles_aprobados": set()
}

bloqueo_eventos = False

# Contenedores gráficos fijos
pantalla_perfil = widgets.Output()
pantalla_ajustes = widgets.Output()
pantalla_controles = widgets.Output()
pantalla_leccion = widgets.Output()

menu_desplegable = widgets.Dropdown(description='⚡ Materia:')
selector_avatar = widgets.Dropdown(description='👤 Icono:')
panel_ajustes = widgets.Accordion(children=[selector_avatar])
panel_ajustes.set_title(0, '⚙️ Ajustes de Perfil')
panel_ajustes.selected_index = None

# Botón para cerrar sesión
btn_cerrar_sesion = widgets.Button(description="Cerrar Sesión 🚪", button_style='warning', layout=widgets.Layout(margin='10px 0 0 0'))

# Componente nativo de barra de progreso
barra_progreso_total = widgets.IntProgress(
    value=0, min=0, max=200, description='Progreso:',
    bar_style='success', style={'bar_color': '#2ecc71'}
)

def calcular_nivel():
    nuevo_nivel = (usuario["xp"] // 50) + 1
    if nuevo_nivel > usuario["nivel"]:
        usuario["nivel"] = nuevo_nivel
        return True
    return False

def actualizar_tarjeta_perfil(notificacion_nivel=""):
    with pantalla_perfil:
        clear_output(wait=True)
        juegos_ganados = len(usuario["niveles_aprobados"])
        barra_progreso_total.value = juegos_ganados
        porcentaje_total = int((juegos_ganados / 200) * 100)

        tarjeta_html = widgets.HTML(value=f"""
        <div style="background-color: #2c3e50; color: white; padding: 15px; border-radius: 10px; margin-bottom: 10px;">
            <div style="{usuario['avatar_estilo']} width: 60px; height: 60px; border-radius: 50%; float: left; margin-right: 15px; border: 3px solid white;"></div>
            <h2 style="margin: 0; padding-top: 5px;">{usuario['nombre']}</h2>
            <p style="margin: 3px 0 0 0; font-weight: bold; color: #f1c40f;">🌟 Nivel {usuario['nivel']} | ✨ {usuario['xp']} XP</p>
            <p style="margin: 5px 0 0 0; font-size: 12px; color: #bdc3c7;">Completado: {juegos_ganados}/200 minijuegos ({porcentaje_total}%)</p>
            <div style="clear: both;"></div>
        </div>
        {notificacion_nivel}
        """)
        display(tarjeta_html, barra_progreso_total, btn_cerrar_sesion)

def inicializar_menus():
    global bloqueo_eventos
    bloqueo_eventos = True

    opciones_materia = {}
    for clave, datos in banco_materias.items():
        resueltos_esta_materia = sum(1 for x in usuario["niveles_aprobados"] if x.startswith(clave))
        opciones_materia[f"{datos['menu_texto']} ({resueltos_esta_materia}/50)"] = clave

    seleccion_actual = menu_desplegable.value
    menu_desplegable.options = opciones_materia
    if seleccion_actual in menu_desplegable.options.values():
        menu_desplegable.value = seleccion_actual

    avatares_disponibles = {}
    for nombre, datos in lista_avatares.items():
        if usuario["nivel"] >= datos["nivel_req"]:
            avatares_disponibles[nombre] = datos["estilo"]
        else:
            avatares_disponibles[f"🔒 {nombre} (Nivel {datos['nivel_req']})"] = "BLOQUEADO"

    selector_avatar.options = avatares_disponibles
    selector_avatar.value = usuario["avatar_estilo"]

    with pantalla_controles:
        clear_output(wait=True)
        display(menu_desplegable)

    with pantalla_ajustes:
        clear_output(wait=True)
        display(panel_ajustes)

    bloqueo_eventos = False

def al_cambiar_materia(change):
    if bloqueo_eventos: return
    if change['type'] == 'change' and change['name'] == 'value' and change['new']:
        cargar_leccion(change['new'])

def al_cambiar_avatar(change):
    if bloqueo_eventos: return
    if change['type'] == 'change' and change['name'] == 'value':
        if change['new'] and change['new'] != "BLOQUEADO":
            usuario["avatar_estilo"] = change['new']
            actualizar_tarjeta_perfil()
            guardar_progreso_usuario() # Guarda el cambio estético de avatar

def al_cerrar_sesion(b):
    # Limpia la pantalla completa y nos regresa al formulario de registro de la Celda 4
    clear_output()
    usuario["nombre"] = ""
    print("🔄 Sesión cerrada. Por favor, ejecuta la Celda 4 para iniciar sesión con otro nombre.")

btn_cerrar_sesion.on_click(al_cerrar_sesion)

def cargar_leccion(id_materia):
    nivel_actual = 1
    for i in range(1, 51):
        if f"{id_materia}_{i}" not in usuario["niveles_aprobados"]:
            nivel_actual = i
            break

    if f"{id_materia}_50" in usuario["niveles_aprobados"]:
        with pantalla_leccion:
            clear_output(wait=True)
            display(widgets.HTML(f"<h2>🏆 ¡Felicidades!</h2><p>Completaste los 50 minijuegos de esta materia.</p>"))
        return

    datos = banco_materias[id_materia]["juegos"][nivel_actual - 1]

    texto_teoria = widgets.HTML(value=f"<h2>📚 {datos['titulo']}</h2><p style='font-size:14px; white-space: pre-wrap;'>{datos['explicacion']}</p>")
    btn_ir_a_jugar = widgets.Button(description="¡Entendido! Jugar 🎮", button_style='success')
    pestana_aprender = widgets.VBox([texto_teoria, btn_ir_a_jugar])

    texto_juego = widgets.HTML(value=f"<h3>🧩 Minijuego ({nivel_actual}/50)</h3><p>{datos['pregunta']}</p>")
    selector = widgets.RadioButtons(options=datos['opciones'], value=None, description='Respuesta:')
    btn_comprobar = widgets.Button(description="Comprobar Respuesta", button_style='info')
    texto_feedback = widgets.HTML(value="")
    contenedor_audio_local = widgets.Output()

    pestana_juego = widgets.VBox([texto_juego, selector, btn_comprobar, texto_feedback, contenedor_audio_local])
    tabs_leccion = widgets.Tab(children=[pestana_aprender, pestana_juego])
    tabs_leccion.set_title(0, '1. Teoría')
    tabs_leccion.set_title(1, '2. Jugar')

    btn_ir_a_jugar.on_click(lambda b: setattr(tabs_leccion, 'selected_index', 1))

    def verificar(b):
        if selector.value == datos['correcta']:
            with contenedor_audio_local:
                clear_output(wait=True)
                display(generar_sonido_acierto())

            clave_nivel = f"{id_materia}_{nivel_actual}"
            aviso_nivel = ""

            if clave_nivel not in usuario["niveles_aprobados"]:
                usuario["niveles_aprobados"].add(clave_nivel)
                usuario["xp"] += 1

                subio = calcular_nivel()
                if subio:
                    aviso_nivel = f"<div style='background-color:#2ecc71; color:white; padding:10px; border-radius:5px; margin-top:5px; font-weight:bold;'>🎉 ¡Subiste de nivel! Nuevo escudo disponible.</div>"

                guardar_progreso_usuario() # 💾 GUARDA PROGRESO TRAS CADA ACIERTO
                actualizar_tarjeta_perfil(aviso_nivel)
                inicializar_menus()

            texto_feedback.value = f"<span style='color:green; font-weight:bold;'>¡Correcto! (+1 XP). Guardando progreso y cargando siguiente nivel...</span>"
            b.disabled = True
            time.sleep(1)
            cargar_leccion(id_materia)
        else:
            with contenedor_audio_local:
                clear_output(wait=True)
                display(generar_sonido_error())
            texto_feedback.value = "<span style='color:red; font-weight:bold;'>Respuesta incorrecta. Revisa la teoría e intenta de nuevo. 🔄</span>"

    btn_comprobar.on_click(verificar)

    with pantalla_leccion:
        clear_output(wait=True)
        display(tabs_leccion)



pip install pyngrok -q
pip install streamlit -q


ngrok config add-authtoken "3G37gpv9lrTMuKL3DHjQ8S5Ee50_2P5Hhgx7g7UNHDjjQZng9"


import os
import time
from pyngrok import ngrok
from IPython.display import clear_output

print("Encendiendo el servidor de Streamlit... 🚀")
os.system("nohup streamlit run app.py --server.port 8501 --server.address 127.0.0.1 > /dev/null 2>&1 &")


time.sleep(5)


ngrok.kill()
clear_output()
enlace_publico = ngrok.connect(8501, "http")

print(f"🔗 ¡Listo! Entra a este nuevo enlace sin errores:")
print(f"👉 {enlace_publico.public_url}")
